oauth:
  kakao:
    client-id: fc6f615cf058940202a5978d5af26736
    client-secret: CWm5ybBNNssGQNDSLPO1N8suSeC0exRw
    redirect-uri: https://i10a807.p.ssafy.io/login
    scope: profile_nickname,profile_image,account_email
spring:
  datasource:
    url: 'jdbc:mariadb://i10a807.p.ssafy.io:3306/haryeom'
    username: root
    password: ssafyioi807
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: i10a807.p.ssafy.io
      port: 6379
    mongodb:
      uri: mongodb://i10a807.p.ssafy.io:27017/haryeom
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jwt:
    token:
      secret-key: QTEwN2phbnNvcnJ5dGVhbWRuZmxya2RsZW1kZ2tmcmpkaWFrZmZsd2xha2RrcnBUc2kK
      refresh-secret-key:
        QTEwN2phbnNvcnJ5dGVhbWZsdm1mcHRubHhoem1zZHBlb2drZ2tzcmtxdGRsc2xSa3Jqc2VtZndsYWsK
  univcert:
    api-key: 959145b3-a495-451e-bef0-1dbd11a96616
cloud:
  aws:
    s3:
      bucket: hjr-bucket
    credentials:
      access-key: AKIA3XBXJOXXC2SZ63GV
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
